config/routes.rb
Rails.application.routes.draw do
  get    "tasks",          to: "tasks#index"

  get    "tasks/new",      to: "tasks#new"
  post   "tasks",          to: "tasks#create"

  # NB: The `show` route needs to be *after* `new` route.
  get    "tasks/:id",      to: "tasks#show", as: :task

  get    "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch  "tasks/:id",      to: "tasks#update"

  delete "tasks/:id",      to: "tasks#destroy", as: :destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<h1>A new task please</h1>
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div>
    <%= f.label "completed" %>
    <%= f.check_box :completed %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form'%>

app/views/tasks/index.html.erb
<h1>My Task</h1>

<% @tasks.each do |t| %>
<ul>
  <div>
    <% if t.completed  %>
      <input type="checkbox" id="check_box" name="check_box" checked>
    <% else %>
      <input type="checkbox" id="check_box" name="check_box">
    <% end %>
    <%= link_to t.title, task_path(t) %>
  </div>
<%= link_to "Delete", destroy_path(t),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</ul>
<% end %>
<%= link_to "create a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>My Task details</h1>

<h2><%= @task.details %></h2>

<p><%= link_to "back to tasks", tasks_path %></p>
<p><%= link_to "edit task", edit_path %></p>